version: "3.8"
services:
  db:
    container_name: autospace_db
    image: postgres
    restart: always
    ports:
    - 2099:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: autospace
    volumes:
      - db_data_autospace:/var/lib/postgresql/data   

volumes:
  db_data_autospace: